### ISSUE TITLE
Is it possible to profile GUI wrappers to vim like gvim or macvim?

### ISSUE THREAD

**Issue by sudar** [bchretien/vim-profiler#1]
Thanks for the wonderful script.

I use macvim and have enabled lot of macvim specific features in my vimrc. When I launch the profiler with the following command

./vim-profiler.py mvim

It opens up macvim but since it runs as a seperate process the profile is not able to process the log file and just prints the following message

```
Running mvim to generate startup logs... done.
Loading and processing logs...
No plugin found. Exiting.
```

If I check the directory, it actually creates a vim log file, but the profiler is not able to process it.

**Comment by bchretien** [comment]
Oh I missed the notification for your issue, sorry for that! I only use terminal vim, so I didn't think about that scenario. I'll fix that soon.

**Comment by bchretien** [comment]
Let me know if that works for you. That was tested on Linux with `gvim`.

**Comment by sudar** [comment]
@bchretien I just checked the updated script with macvim and it works perfectly.

Thanks!

**Comment by bchretien** [comment]
Perfect, thanks for the report!
