### ISSUE TITLE
Consider a merge?

### ISSUE THREAD

**Issue by hyiltiz** [bchretien/vim-profiler#3]
Hi @bchretien,

You indicated here that your project was based on a similar project of mine. The project now already includes other languages such as Ruby which is independent of R. Would you like to merge your Python implementation?

http://stackoverflow.com/questions/1687799/profiling-vim-startup-time/33194019#33194019

**Comment by hyiltiz** [comment]
After a long silence, I am going to merge your python implementation with my Ruby/R implementation. We are compatible by the GPL.

**Comment by bchretien** [comment]
Hi,

Sorry for the long delay, I tend to miss quite a lot of notifications lately. I don't really see the point of merging implementations in different languages in the same repository.

Also, there are other similar projects (e.g. [startup.vim](https://github.com/tweekmonster/startuptime.vim)). There's been talk on the subjects on the [neovim issue tracker](https://github.com/neovim/neovim/issues/6182).

**Comment by hyiltiz** [comment]
Glad you pointed me to the neovim issue tracker. A lovely discussion. Thanks!
